/* Copyright (c) Microsoft Corporation.
   Licensed under the MIT License. */

/* Copyright (c) Microsoft Corporation.
   Licensed under the MIT License. */

/***************************************************************************

	CHOMP.H
	Header file for Chomp, the chunky compiler

***************************************************************************/
#ifndef CHOMP_H
#define CHOMP_H

#include <stdio.h>
#include "../../kauai/SRC/FRAME.H"
#include "../../kauai/SRC/mssio.h"

#endif //!CHOMP_H

